version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src            # mount only source code
      - ./public:/app/public      # mount public assets
      - node_modules:/app/node_modules  # keep modules in container
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true  # enable polling for live reload
    command: npm start

volumes:
  node_modules:
